### ISSUE TITLE
Using Buffer without `new` will soon stop working.

### ISSUE THREAD

**Issue by chuck-durst** [Mithgol/dauria#2]
Hi,

I'm currently using dauria for a node/express project. when calling to the getBase64DataURI() function, node returns me the following warning: 

> (node:6834) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

node version: 7.2.0

This isn't a big deal actually but it might cause troubles with an upper node version.

**Comment by Mithgol** [comment]
I've decided to use `new Buffer(…)` because `Buffer.from` is only supported in Node.js version 5.10.0 (2016-04-01) or newer.

I might start using `Buffer.from` when I decide to stop supporting older Node.js versions in the future.
